### ISSUE TITLE
window example panics on Sway 0.15.2

### ISSUE THREAD

**Issue by majewsky** [tomaka/glutin#1017]
```
$ git rev-parse HEAD        
6658ae58ec7705d3fea598feea0d5d6f43d83101
```
```
$ RUST_BACKTRACE=1 cargo run --example window
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/examples/window`
wl_registry@2: error 0: invalid version for global wl_seat (5): have 4, wanted 5
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 71, kind: Other, message: "Protocol error" }', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: std::panicking::begin_panic_fmt
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::result::unwrap_failed
             at /build/rust/src/rustc-1.25.0-src/src/libcore/macros.rs:23
  10: <core::result::Result<T, E>>::unwrap
             at /build/rust/src/rustc-1.25.0-src/src/libcore/result.rs:782
  11: winit::platform::platform::wayland::window::Window::new
             at /home/stefan/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.12.0/src/platform/linux/wayland/window.rs:77
  12: winit::platform::platform::Window::new
             at /home/stefan/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.12.0/src/platform/linux/mod.rs:116
  13: winit::window::<impl winit::WindowBuilder>::build
             at /home/stefan/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.12.0/src/window.rs:119
  14: glutin::platform::platform::wayland::Context::new
             at src/platform/linux/wayland.rs:23
  15: glutin::platform::platform::Context::new
             at src/platform/linux/mod.rs:47
  16: glutin::GlWindow::new
             at src/lib.rs:313
  17: window::main
             at examples/window.rs:11
  18: std::rt::lang_start::{{closure}}
             at /build/rust/src/rustc-1.25.0-src/src/libstd/rt.rs:74
  19: std::panicking::try::do_call
  20: __rust_maybe_catch_panic
  21: std::rt::lang_start_internal
  22: std::rt::lang_start
             at /build/rust/src/rustc-1.25.0-src/src/libstd/rt.rs:74
  23: main
  24: __libc_start_main
  25: _start
```

It works fine with `WINIT_UNIX_BACKEND=x11`, though. The compositor is [Sway](https://github.com/swaywm/sway):

```
$ sway --version
sway version 0.15.2
```
```sh
$ cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
```

**Comment by vberger** [comment]
This is actually an issue with winit, not glutin. Closing in favor of https://github.com/tomaka/winit/issues/485 .
