### ISSUE TITLE
GL context creation failed on X11

### ISSUE THREAD

**Issue by aepsil0n** [tomaka/glutin#314]
I'm getting this error running the `window` example on the latest master of glutin.

```
[glutin] x error code=2 major=-102 minor=34!
[glutin] x error code=2 major=-102 minor=3!
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: OsError("GL context creation failed")', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:744
```

**Comment by aepsil0n** [comment]
Can anybody reproduce this? If not, any ideas how to track it down?

**Comment by glennw** [comment]
I can't reproduce it here. But you could try one or both of these steps:

1) Disable the glutin X error handler - https://github.com/tomaka/glutin/blob/master/src/x11/window/mod.rs#L34 - this *might* result in X writing a more descriptive error message on the console that you can post here.

2) With the X error handler enabled, run gdb and place a breakpoint in https://github.com/tomaka/glutin/blob/master/src/x11/window/mod.rs - then paste the backtrace from gdb here (this will allow us to at least see which X/GL function call is failing).

**Comment by tomaka** [comment]
Error code 2 is `BadValue`.

Seeing the error, it can be either `glXCreateContext` or `glXCreateContextAttribsARB` that fails.

For `glXCreateContext`:
> BadValue is generated if vis is not a valid visual (for
            example, if a particular GLX implementation does not support it).

For `glXCreateContextAttribsARB`:
> If attribute GLX_RENDER_TYPE does not describe a valid rendering
        type, BadValue is generated.

> If an attribute or attribute value in <attrib_list>
        is not recognized (including unrecognized bits in bitmask
        attributes), BadValue is generated.

It's maybe a problem with an old version of X11?

**Comment by glennw** [comment]
Ah, that's a good point - if you can paste the output of "glxgears -info" here, that may help too - perhaps an old/buggy GLX implementation or something like that.

**Comment by aepsil0n** [comment]
Hm… now I can't reproduce it myself. The glutin version in which it did occur first does not compile any more and on the latest master it does not appear. I did update my system in the mean time, however, so can't be sure where the issue was.

**Comment by zetok** [comment]
I could reproduce with examples `window` and `transparent`, compiled with ``Rust 1.2.0``.

OS: Hardened Gentoo x86_64
Xorg: ``1.17.1-r1``


```
$ RUST_BACKTRACE=1 cargo run --example transparent
   Compiling glutin v0.3.4 (file:///home/zetok/git_zetok/rust/glutin)
examples/support/mod.rs:69:13: 69:21 warning: unused import, #[warn(unused_imports)] on by default
examples/support/mod.rs:69         use std::mem;
                                       ^~~~~~~~
examples/transparent.rs:27:5: 27:38 warning: unused result which must be used, #[warn(unused_must_use)] on by default
examples/transparent.rs:27     unsafe { window.make_current() };
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
examples/transparent.rs:35:9: 35:31 warning: unused result which must be used, #[warn(unused_must_use)] on by default
examples/transparent.rs:35         window.swap_buffers();
                                   ^~~~~~~~~~~~~~~~~~~~~~
note: in expansion of for loop expansion
examples/transparent.rs:33:5: 43:6 note: expansion site
     Running `target/debug/examples/transparent`
thread '<main>' panicked at 'eglCreateContext failed: 0x3009', src/api/egl/mod.rs:631
stack backtrace:
   1:     0x7f988d745ffe - sys::backtrace::write::h31b60a04d5b9a81ckqs
   2:     0x7f988d749605 - panicking::on_panic::haca2ec19b0bb0f31B8w
   3:     0x7f988d741cce - rt::unwind::begin_unwind_inner::h384bd76ff13d8e66fOw
   4:     0x7f988d74228c - rt::unwind::begin_unwind_fmt::hf78032cbbe2296b5lNw
   5:     0x7f988d639cbb - api::egl::create_context::h1d46f5bfae55f297xgc
                        at /home/zetok/git_zetok/rust/glutin/<std macros>:8
   6:     0x7f988d638c00 - api::egl::ContextPrototype<'a>::finish_impl::hdf3f8e3952a1a811ZUb
                        at src/api/egl/mod.rs:381
   7:     0x7f988d638493 - api::egl::ContextPrototype<'a>::finish::h5dc32d1b4cb6a188nSb
                        at src/api/egl/mod.rs:331
   8:     0x7f988d6789d8 - api::x11::window::Window::new::h3619c3be1f101069yVf
                        at src/api/x11/window.rs:527
   9:     0x7f988d682c5e - platform::platform::api_dispatch::Window::new::hd867ff1179439844QLg
                        at src/platform/linux/api_dispatch.rs:155
  10:     0x7f988d68976f - window::WindowBuilder<'a>::build::hb9dad08642779f7difj
                        at src/window.rs:182
  11:     0x7f988d6152fb - main::hea5da600bc8d64ddBAc
                        at examples/transparent.rs:22
  12:     0x7f988d74e488 - rust_try_inner
  13:     0x7f988d74e475 - rust_try
  14:     0x7f988d74b138 - rt::lang_start::hee8a643f234925aay3w
  15:     0x7f988d61d40b - main
  16:     0x7f988d045e7a - __libc_start_main
  17:     0x7f988d60d508 - <unknown>
  18:                0x0 - <unknown>
An unknown error occurred

To learn more, run the command again with --verbose.
```


Output of `glxgears -info`:
```
$ glxgears -info
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
GL_RENDERER   = Gallium 0.4 on AMD RS780
GL_VERSION    = 2.1 Mesa 10.3.7
GL_VENDOR     = X.Org
GL_EXTENSIONS = GL_ARB_multisample GL_EXT_abgr GL_EXT_bgra GL_EXT_blend_color GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_copy_texture GL_EXT_polygon_offset GL_EXT_subtexture GL_EXT_texture_object GL_EXT_vertex_array GL_EXT_compiled_vertex_array GL_EXT_texture GL_EXT_texture3D GL_IBM_rasterpos_clip GL_ARB_point_parameters GL_EXT_draw_range_elements GL_EXT_packed_pixels GL_EXT_point_parameters GL_EXT_rescale_normal GL_EXT_separate_specular_color GL_EXT_texture_edge_clamp GL_SGIS_generate_mipmap GL_SGIS_texture_border_clamp GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod GL_ARB_framebuffer_sRGB GL_ARB_multitexture GL_EXT_framebuffer_sRGB GL_IBM_multimode_draw_arrays GL_IBM_texture_mirrored_repeat GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_transpose_matrix GL_EXT_blend_func_separate GL_EXT_fog_coord GL_EXT_multi_draw_arrays GL_EXT_secondary_color GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_lod_bias GL_INGR_blend_func_separate GL_NV_blend_square GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_env_combine4 GL_S3_s3tc GL_SUN_multi_draw_arrays GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_EXT_framebuffer_object GL_EXT_texture_compression_s3tc GL_EXT_texture_env_combine GL_EXT_texture_env_dot3 GL_MESA_window_pos GL_NV_packed_depth_stencil GL_NV_texture_rectangle GL_ARB_depth_texture GL_ARB_occlusion_query GL_ARB_shadow GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_mirrored_repeat GL_ARB_window_pos GL_EXT_stencil_two_side GL_EXT_texture_cube_map GL_NV_depth_clamp GL_NV_fog_distance GL_APPLE_packed_pixels GL_APPLE_vertex_array_object GL_ARB_draw_buffers GL_ARB_fragment_program GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_vertex_program GL_ARB_vertex_shader GL_ATI_draw_buffers GL_ATI_texture_env_combine3 GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_MESA_pack_invert GL_NV_primitive_restart GL_ARB_depth_clamp GL_ARB_fragment_program_shadow GL_ARB_half_float_pixel GL_ARB_occlusion_query2 GL_ARB_point_sprite GL_ARB_shading_language_100 GL_ARB_sync GL_ARB_texture_non_power_of_two GL_ARB_vertex_buffer_object GL_ATI_blend_equation_separate GL_EXT_blend_equation_separate GL_OES_read_format GL_ARB_color_buffer_float GL_ARB_pixel_buffer_object GL_ARB_texture_compression_rgtc GL_ARB_texture_rectangle GL_ATI_texture_compression_3dc GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_mirror_clamp GL_EXT_texture_rectangle GL_EXT_texture_sRGB GL_EXT_texture_shared_exponent GL_ARB_framebuffer_object GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_packed_depth_stencil GL_ARB_vertex_array_object GL_ATI_separate_stencil GL_ATI_texture_mirror_once GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_gpu_program_parameters GL_EXT_texture_array GL_EXT_texture_compression_latc GL_EXT_texture_integer GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_OES_EGL_image GL_ARB_copy_buffer GL_ARB_depth_buffer_float GL_ARB_draw_instanced GL_ARB_half_float_vertex GL_ARB_instanced_arrays GL_ARB_map_buffer_range GL_ARB_texture_rg GL_ARB_texture_swizzle GL_ARB_vertex_array_bgra GL_EXT_texture_swizzle GL_EXT_vertex_array_bgra GL_NV_conditional_render GL_AMD_conservative_depth GL_AMD_draw_buffers_blend GL_AMD_shader_stencil_export GL_ARB_ES2_compatibility GL_ARB_blend_func_extended GL_ARB_debug_output GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_explicit_attrib_location GL_ARB_fragment_coord_conventions GL_ARB_provoking_vertex GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_shader_stencil_export GL_ARB_shader_texture_lod GL_ARB_texture_multisample GL_ARB_texture_rgb10_a2ui GL_ARB_uniform_buffer_object GL_ARB_vertex_type_2_10_10_10_rev GL_EXT_provoking_vertex GL_EXT_texture_snorm GL_MESA_texture_signed_rgba GL_NV_texture_barrier GL_ARB_get_program_binary GL_ARB_robustness GL_ARB_separate_shader_objects GL_ARB_shader_bit_encoding GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_base_instance GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_internalformat_query GL_ARB_map_buffer_alignment GL_ARB_shading_language_420pack GL_ARB_shading_language_packing GL_ARB_texture_storage GL_ARB_transform_feedback_instanced GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_transform_feedback GL_AMD_shader_trinary_minmax GL_ARB_ES3_compatibility GL_ARB_clear_buffer_object GL_ARB_explicit_uniform_location GL_ARB_invalidate_subdata GL_ARB_stencil_texturing GL_ARB_texture_query_levels GL_ARB_texture_storage_multisample GL_ARB_vertex_attrib_binding GL_KHR_debug GL_ARB_buffer_storage GL_ARB_multi_bind GL_ARB_texture_mirror_clamp_to_edge GL_ARB_vertex_type_10f_11f_11f_rev GL_EXT_shader_integer_mix GL_ARB_texture_barrier 
VisualID 537, 0x219
239 frames in 5.0 seconds = 47.797 FPS
291 frames in 5.0 seconds = 58.191 FPS
288 frames in 5.0 seconds = 57.591 FPS
268 frames in 5.0 seconds = 53.593 FPS
285 frames in 5.0 seconds = 56.992 FPS
```

**Comment by tomaka** [comment]
Some notes for myself (or for whoever wants to fix this):

Value `0x3009` means `EGL_BAD_MATCH`.

Pages 55 to 57 of the EGL 1.5 specs:

> An
EGL_BAD_MATCH
error  is  generated  if  the  current  rendering  api  is
EGL_NONE
(this situation can only arise in an implementation which does not
support OpenGL ES 1.x, and prior to the first call to
eglBindAPI
).
> An
EGL_BAD_MATCH
error  is  generated  if
config
does  not  support  the
requested  client  API.  This  includes  requesting  creation  of  an  OpenGL  ES
1.x, 2.0, or 3.0 context when the
EGL_RENDERABLE_TYPE
attribute of
config
does not contain
EGL_OPENGL_ES_BIT
,
EGL_OPENGL_ES2_BIT
, or
EGL_-
OPENGL_ES3_BIT
respectively.
An
EGL_BAD_MATCH
error is generated if an OpenGL or OpenGL ES con-
text is requested and any of:

the server context state for
share
context
exists in an address space that
cannot be shared with the newly created context

share
context
was created on a different display than the one referenced
by
config

the reset notification behavior of
share
context
and the newly created
context are different

the contexts are otherwise incompatible (for example, one context being
associated with a hardware device driver and the other with a software
renderer).
An
EGL_BAD_MATCH
error is generated if an OpenGL or OpenGL ES con-
text is requested and the specified version number is not a defined version of
that client API.
An
EGL_BAD_MATCH
error is generated if an forward-compatible OpenGL
context is requested and the
requested
OpenGL version is less than 3.0, or the
implementation does not support a forward-compatible context of exactly the
requested version.  Because the purpose of forward-compatible contexts is to
allow application development on a specific OpenGL version with the knowl-
edge that the app will run on a future version,  in this case context creation
cannot result in a later, backwards-compatible version.
An
EGL_BAD_MATCH
error is generated if an OpenGL or OpenGL ES con-
text is requested with robust buffer access, and the implementation does not
support the corresponding OpenGL or OpenGL ES extension.
An
EGL_BAD_MATCH
error is generated if an OpenGL or OpenGL ES con-
text is requested with robust buffer access and with a specified reset notifica-
EGL 1.5 - August 27, 2014
3.7. RENDERING CONTEXTS
57
tion behavior, and the implementation does not support that behavior.
An
EGL_BAD_MATCH
error is generated if an OpenGL context is requested,
the requested version is 3.2 or greater, and any of:

the context profile mask has no bits set

the mask has any bits set other than
EGL_CONTEXT_OPENGL_CORE_-
PROFILE_BIT
and
EGL_CONTEXT_OPENGL_COMPATIBILITY_-
PROFILE_BIT

the mask has more than one of these bits set

the implementation does not support the requested profile.
An
EGL_BAD_MATCH
error is generated if
config
does not support a context
compatible with the requested API version and context attributes for reasons
not enumerated above.  It is difficult to enumerate all possible combinations
of unsupported context  version attributes,  since  this sometimes depends on
properties of the implementation;  this error allows such implementations to
indicate they cannot satisfy a request.

**Comment by tomaka** [comment]
@zetok Could you paste what `glxinfo` says?
I'm looking for the version and extensions of EGL.

**Comment by tomaka** [comment]
Oh it's maybe simply because the function panicks instead of returning an error in case the version is not supported.

**Comment by zetok** [comment]
```
$ glxinfo
name of display: :0.0
display: :0  screen: 0
direct rendering: Yes
server glx vendor string: SGI
server glx version string: 1.4
server glx extensions:
    GLX_ARB_create_context, GLX_ARB_create_context_profile, 
    GLX_ARB_fbconfig_float, GLX_ARB_framebuffer_sRGB, GLX_ARB_multisample, 
    GLX_EXT_create_context_es2_profile, GLX_EXT_framebuffer_sRGB, 
    GLX_EXT_import_context, GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, 
    GLX_EXT_visual_rating, GLX_INTEL_swap_event, GLX_MESA_copy_sub_buffer, 
    GLX_OML_swap_method, GLX_SGIS_multisample, GLX_SGIX_fbconfig, 
    GLX_SGIX_pbuffer, GLX_SGIX_visual_select_group, GLX_SGI_swap_control
client glx vendor string: Mesa Project and SGI
client glx version string: 1.4
client glx extensions:
    GLX_ARB_create_context, GLX_ARB_create_context_profile, 
    GLX_ARB_create_context_robustness, GLX_ARB_fbconfig_float, 
    GLX_ARB_framebuffer_sRGB, GLX_ARB_get_proc_address, GLX_ARB_multisample, 
    GLX_EXT_buffer_age, GLX_EXT_create_context_es2_profile, 
    GLX_EXT_fbconfig_packed_float, GLX_EXT_framebuffer_sRGB, 
    GLX_EXT_import_context, GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, 
    GLX_EXT_visual_rating, GLX_INTEL_swap_event, GLX_MESA_copy_sub_buffer, 
    GLX_MESA_multithread_makecurrent, GLX_MESA_query_renderer, 
    GLX_MESA_swap_control, GLX_OML_swap_method, GLX_OML_sync_control, 
    GLX_SGIS_multisample, GLX_SGIX_fbconfig, GLX_SGIX_pbuffer, 
    GLX_SGIX_visual_select_group, GLX_SGI_make_current_read, 
    GLX_SGI_swap_control, GLX_SGI_video_sync
GLX version: 1.4
GLX extensions:
    GLX_ARB_create_context, GLX_ARB_create_context_profile, 
    GLX_ARB_fbconfig_float, GLX_ARB_framebuffer_sRGB, 
    GLX_ARB_get_proc_address, GLX_ARB_multisample, 
    GLX_EXT_create_context_es2_profile, GLX_EXT_framebuffer_sRGB, 
    GLX_EXT_import_context, GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, 
    GLX_EXT_visual_rating, GLX_INTEL_swap_event, GLX_MESA_copy_sub_buffer, 
    GLX_MESA_multithread_makecurrent, GLX_MESA_query_renderer, 
    GLX_MESA_swap_control, GLX_OML_swap_method, GLX_OML_sync_control, 
    GLX_SGIS_multisample, GLX_SGIX_fbconfig, GLX_SGIX_pbuffer, 
    GLX_SGIX_visual_select_group, GLX_SGI_make_current_read, 
    GLX_SGI_swap_control, GLX_SGI_video_sync
OpenGL vendor string: X.Org
OpenGL renderer string: Gallium 0.4 on AMD RS780
OpenGL version string: 2.1 Mesa 10.3.7
OpenGL shading language version string: 1.30
OpenGL extensions:
    GL_AMD_conservative_depth, GL_AMD_draw_buffers_blend, 
    GL_AMD_shader_stencil_export, GL_AMD_shader_trinary_minmax, 
    GL_ANGLE_texture_compression_dxt3, GL_ANGLE_texture_compression_dxt5, 
    GL_APPLE_packed_pixels, GL_APPLE_vertex_array_object, 
    GL_ARB_ES2_compatibility, GL_ARB_ES3_compatibility, GL_ARB_base_instance, 
    GL_ARB_blend_func_extended, GL_ARB_buffer_storage, 
    GL_ARB_clear_buffer_object, GL_ARB_color_buffer_float, 
    GL_ARB_compressed_texture_pixel_storage, GL_ARB_conservative_depth, 
    GL_ARB_copy_buffer, GL_ARB_debug_output, GL_ARB_depth_buffer_float, 
    GL_ARB_depth_clamp, GL_ARB_depth_texture, GL_ARB_draw_buffers, 
    GL_ARB_draw_buffers_blend, GL_ARB_draw_elements_base_vertex, 
    GL_ARB_draw_instanced, GL_ARB_explicit_attrib_location, 
    GL_ARB_explicit_uniform_location, GL_ARB_fragment_coord_conventions, 
    GL_ARB_fragment_program, GL_ARB_fragment_program_shadow, 
    GL_ARB_fragment_shader, GL_ARB_framebuffer_object, 
    GL_ARB_framebuffer_sRGB, GL_ARB_get_program_binary, 
    GL_ARB_half_float_pixel, GL_ARB_half_float_vertex, 
    GL_ARB_instanced_arrays, GL_ARB_internalformat_query, 
    GL_ARB_invalidate_subdata, GL_ARB_map_buffer_alignment, 
    GL_ARB_map_buffer_range, GL_ARB_multi_bind, GL_ARB_multisample, 
    GL_ARB_multitexture, GL_ARB_occlusion_query, GL_ARB_occlusion_query2, 
    GL_ARB_pixel_buffer_object, GL_ARB_point_parameters, GL_ARB_point_sprite, 
    GL_ARB_provoking_vertex, GL_ARB_robustness, GL_ARB_sampler_objects, 
    GL_ARB_seamless_cube_map, GL_ARB_separate_shader_objects, 
    GL_ARB_shader_bit_encoding, GL_ARB_shader_objects, 
    GL_ARB_shader_stencil_export, GL_ARB_shader_texture_lod, 
    GL_ARB_shading_language_100, GL_ARB_shading_language_420pack, 
    GL_ARB_shading_language_packing, GL_ARB_shadow, GL_ARB_stencil_texturing, 
    GL_ARB_sync, GL_ARB_texture_barrier, GL_ARB_texture_border_clamp, 
    GL_ARB_texture_compression, GL_ARB_texture_compression_rgtc, 
    GL_ARB_texture_cube_map, GL_ARB_texture_env_add, 
    GL_ARB_texture_env_combine, GL_ARB_texture_env_crossbar, 
    GL_ARB_texture_env_dot3, GL_ARB_texture_mirror_clamp_to_edge, 
    GL_ARB_texture_mirrored_repeat, GL_ARB_texture_multisample, 
    GL_ARB_texture_non_power_of_two, GL_ARB_texture_query_levels, 
    GL_ARB_texture_rectangle, GL_ARB_texture_rg, GL_ARB_texture_rgb10_a2ui, 
    GL_ARB_texture_storage, GL_ARB_texture_storage_multisample, 
    GL_ARB_texture_swizzle, GL_ARB_timer_query, GL_ARB_transform_feedback2, 
    GL_ARB_transform_feedback3, GL_ARB_transform_feedback_instanced, 
    GL_ARB_transpose_matrix, GL_ARB_uniform_buffer_object, 
    GL_ARB_vertex_array_bgra, GL_ARB_vertex_array_object, 
    GL_ARB_vertex_attrib_binding, GL_ARB_vertex_buffer_object, 
    GL_ARB_vertex_program, GL_ARB_vertex_shader, 
    GL_ARB_vertex_type_10f_11f_11f_rev, GL_ARB_vertex_type_2_10_10_10_rev, 
    GL_ARB_window_pos, GL_ATI_blend_equation_separate, GL_ATI_draw_buffers, 
    GL_ATI_separate_stencil, GL_ATI_texture_compression_3dc, 
    GL_ATI_texture_env_combine3, GL_ATI_texture_mirror_once, GL_EXT_abgr, 
    GL_EXT_bgra, GL_EXT_blend_color, GL_EXT_blend_equation_separate, 
    GL_EXT_blend_func_separate, GL_EXT_blend_minmax, GL_EXT_blend_subtract, 
    GL_EXT_compiled_vertex_array, GL_EXT_copy_texture, GL_EXT_draw_buffers2, 
    GL_EXT_draw_instanced, GL_EXT_draw_range_elements, GL_EXT_fog_coord, 
    GL_EXT_framebuffer_blit, GL_EXT_framebuffer_multisample, 
    GL_EXT_framebuffer_multisample_blit_scaled, GL_EXT_framebuffer_object, 
    GL_EXT_framebuffer_sRGB, GL_EXT_gpu_program_parameters, 
    GL_EXT_multi_draw_arrays, GL_EXT_packed_depth_stencil, 
    GL_EXT_packed_float, GL_EXT_packed_pixels, GL_EXT_pixel_buffer_object, 
    GL_EXT_point_parameters, GL_EXT_polygon_offset, GL_EXT_provoking_vertex, 
    GL_EXT_rescale_normal, GL_EXT_secondary_color, 
    GL_EXT_separate_specular_color, GL_EXT_shader_integer_mix, 
    GL_EXT_shadow_funcs, GL_EXT_stencil_two_side, GL_EXT_stencil_wrap, 
    GL_EXT_subtexture, GL_EXT_texture, GL_EXT_texture3D, 
    GL_EXT_texture_array, GL_EXT_texture_compression_dxt1, 
    GL_EXT_texture_compression_latc, GL_EXT_texture_compression_rgtc, 
    GL_EXT_texture_compression_s3tc, GL_EXT_texture_cube_map, 
    GL_EXT_texture_edge_clamp, GL_EXT_texture_env_add, 
    GL_EXT_texture_env_combine, GL_EXT_texture_env_dot3, 
    GL_EXT_texture_filter_anisotropic, GL_EXT_texture_integer, 
    GL_EXT_texture_lod_bias, GL_EXT_texture_mirror_clamp, 
    GL_EXT_texture_object, GL_EXT_texture_rectangle, GL_EXT_texture_sRGB, 
    GL_EXT_texture_sRGB_decode, GL_EXT_texture_shared_exponent, 
    GL_EXT_texture_snorm, GL_EXT_texture_swizzle, GL_EXT_timer_query, 
    GL_EXT_transform_feedback, GL_EXT_vertex_array, GL_EXT_vertex_array_bgra, 
    GL_IBM_multimode_draw_arrays, GL_IBM_rasterpos_clip, 
    GL_IBM_texture_mirrored_repeat, GL_INGR_blend_func_separate, GL_KHR_debug, 
    GL_MESA_pack_invert, GL_MESA_texture_signed_rgba, GL_MESA_window_pos, 
    GL_NV_blend_square, GL_NV_conditional_render, GL_NV_depth_clamp, 
    GL_NV_fog_distance, GL_NV_light_max_exponent, GL_NV_packed_depth_stencil, 
    GL_NV_primitive_restart, GL_NV_texgen_reflection, GL_NV_texture_barrier, 
    GL_NV_texture_env_combine4, GL_NV_texture_rectangle, GL_OES_EGL_image, 
    GL_OES_read_format, GL_S3_s3tc, GL_SGIS_generate_mipmap, 
    GL_SGIS_texture_border_clamp, GL_SGIS_texture_edge_clamp, 
    GL_SGIS_texture_lod, GL_SUN_multi_draw_arrays

OpenGL ES profile version string: OpenGL ES 2.0 Mesa 10.3.7
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
OpenGL ES profile extensions:
    GL_ANGLE_texture_compression_dxt3, GL_ANGLE_texture_compression_dxt5, 
    GL_APPLE_texture_max_level, GL_EXT_blend_minmax, 
    GL_EXT_discard_framebuffer, GL_EXT_map_buffer_range, 
    GL_EXT_multi_draw_arrays, GL_EXT_read_format_bgra, 
    GL_EXT_separate_shader_objects, GL_EXT_texture_compression_dxt1, 
    GL_EXT_texture_filter_anisotropic, GL_EXT_texture_format_BGRA8888, 
    GL_EXT_texture_rg, GL_EXT_texture_type_2_10_10_10_REV, 
    GL_EXT_unpack_subimage, GL_NV_draw_buffers, GL_NV_fbo_color_attachments, 
    GL_NV_read_buffer, GL_OES_EGL_image, GL_OES_EGL_image_external, 
    GL_OES_compressed_ETC1_RGB8_texture, GL_OES_depth24, GL_OES_depth_texture, 
    GL_OES_depth_texture_cube_map, GL_OES_element_index_uint, 
    GL_OES_fbo_render_mipmap, GL_OES_get_program_binary, GL_OES_mapbuffer, 
    GL_OES_packed_depth_stencil, GL_OES_rgb8_rgba8, 
    GL_OES_standard_derivatives, GL_OES_stencil8, GL_OES_surfaceless_context, 
    GL_OES_texture_3D, GL_OES_texture_npot, GL_OES_vertex_array_object
```
