### ISSUE TITLE
Headless rendering fails on OS X with "not yet implemented" on is_current

### ISSUE THREAD

**Issue by iburinoc** [tomaka/glutin#737]
Attempting to create a headless renderer on OS X through glium, i.e. `glium::glutin::HeadlessRendererBuilder::new(1024, 768).build_glium().unwrap()`, produces a not yet implemented panic at `is_current` in `src/api/cocoa/headless.rs` :

```
     Running `target/debug/my_project`
thread '<main>' panicked at 'not yet implemented', /Users/Sean/.cargo/registry/src/github.com-88ac128001ac3a9a/glutin-0.4.9/src/api/cocoa/headless.rs:64
thread '<main>' panicked at 'not yet implemented', /Users/Sean/.cargo/registry/src/github.com-88ac128001ac3a9a/glutin-0.4.9/src/api/cocoa/headless.rs:64
stack backtrace:
   1:        0x102993d38 - sys::backtrace::tracing::imp::write::h891a4a9fcda67dccF4t
   2:        0x10299544f - panicking::default_handler::_<closure>::closure.41940
   3:        0x102994ecf - panicking::default_handler::hde0cb232bc545756U3x
   4:        0x10298db54 - sys_common::unwind::begin_unwind_inner::haeb4c6adcf4eff3cF7s
   5:        0x1028895f7 - sys_common::unwind::begin_unwind::h14381684562876497187
   6:        0x1028c349d - api::cocoa::headless::HeadlessContext.GlContext::is_current::h446dc05c53d877d2coa
   7:        0x1028c3444 - headless::HeadlessContext::is_current::hc469ccae3e2c0869p5d
   8:        0x1028c1fa4 - backend::glutin_backend::GlutinHeadlessBackend.Backend::is_current::hc57399ddba463dddvra
   9:        0x1028c1f81 - backend::Rc<T>.Backend::is_current::h11505715463392839453
  10:        0x1028858ec - context::Context.Drop::drop::h3f0424c84cbb275c0fW
  11:        0x10288582f - context..Context::drop.67065::h0fad5be19473727f
  12:        0x10288558f - rc::Rc<T>.Drop::drop::h1321694956537397255
  13:        0x1028854dd - alloc..rc..Rc<context..Context>::drop.67050::ha896448609451466
  14:        0x1028a04c8 - context::Context::new::h6039867758143597725
  15:        0x1028c24da - backend::glutin_backend::glutin..HeadlessRendererBuilder<'a>.DisplayBuild::build_glium_unchecked_debug::hc260c0c8c51558f7Aka
  16:        0x102832d3f - DisplayBuild::build_glium_unchecked::h5726715430457354141
  17:        0x102825ec4 - main::h463d2a4ccd364aa2cOc
  18:        0x102994b02 - sys_common::unwind::try::try_fn::h5317933650159713495
  19:        0x1029932d8 - __rust_try
  20:        0x1029949a5 - rt::lang_start::hcf1bb0740bf735368Vx
  21:        0x10287ef99 - main
thread panicked while panicking. aborting.
An unknown error occurred

To learn more, run the command again with --verbose.
```

The error occurs when using build_glium_unchecked as well.

**Comment by ZeGentzy** [comment]
Fixed.
