### ISSUE TITLE
Builds panicking when built for x86_64-unknown-linux-musl target

### ISSUE THREAD

**Issue by L117** [tomaka/glutin#891]
Not sure if this target supported by `glutin`, but builds are panicking:
```
$ RUST_BACKTRACE=1 cargo run --release --example window --target x86_64-unknown-linux-musl
    Finished release [optimized] target(s) in 0.1 secs
     Running `target/x86_64-unknown-linux-musl/release/examples/window`
thread 'main' panicked at 'Attempted to create an EventsLoop while no backend was available.', /home/k117/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.6.4/src/platform/linux/mod.rs:316
stack backtrace:
   1:     0x5630ac275d59 - std::sys::imp::backtrace::tracing::imp::write::hbb14611794d3841b
                        at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x5630ac27837e - std::panicking::default_hook::{{closure}}::h6ed906c7818ac88c
                        at /checkout/src/libstd/panicking.rs:351
   3:     0x5630ac277f84 - std::panicking::default_hook::h23eeafbf7c1c05c3
                        at /checkout/src/libstd/panicking.rs:367
   4:     0x5630ac2787db - std::panicking::rust_panic_with_hook::hd0067971b6d1240e
                        at /checkout/src/libstd/panicking.rs:545
   5:     0x5630ac22809f - std::panicking::begin_panic::h0c94784039594bde
   6:     0x5630ac235e55 - winit::platform::platform::EventsLoop::new::hc9d4af81b6c6d23d
   7:     0x5630ac237ca0 - winit::EventsLoop::new::h4e2f62d701f74295
   8:     0x5630ac213fce - glutin::platform::platform::api_dispatch::EventsLoop::new::hfb27ec5c16414d49
   9:     0x5630ac2259c0 - glutin::EventsLoop::new::h41360583a2c9b4a3
  10:     0x5630ac206ecd - window::main::hc8e3dfcf7c73e592
  11:     0x5630ac2808fa - __rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:98
  12:     0x5630ac278e2e - std::rt::lang_start::hb7fc7ec87b663023
                        at /checkout/src/libstd/panicking.rs:429
                        at /checkout/src/libstd/panic.rs:361
                        at /checkout/src/libstd/rt.rs:57
```

**Comment by francesca64** [comment]
- Does this still happen?
- Are you expecting X11, or Wayland? (and what are the installed versions of each?)

**Comment by ZeGentzy** [comment]
Closing for inactivity. Feel free to reopen if still an issue.
