### ISSUE TITLE
GlWindow creation fails on Win10

### ISSUE THREAD

**Issue by msiglreith** [tomaka/glutin#906]
I'm trying to run the [`window`](https://github.com/tomaka/glutin/blob/master/examples/window.rs) example on the master but it crashes at https://github.com/tomaka/glutin/blob/master/examples/window.rs#L11

OS: Windows 10
rustc 1.18.0 (03fc9d622 2017-06-06)

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\libcore\option.rs:329
note: Run with `RUST_BACKTRACE=1` for a backtrace.
^C
E:\Desktop\glutin-master>set RUST_BACKTRACE=1

E:\Desktop\glutin-master>cargo run --example window
    Finished dev [unoptimized + debuginfo] target(s) in 0.1 secs
     Running `target\debug\examples\window.exe`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\libcore\option.rs:329
stack backtrace:
   0: std::sys_common::backtrace::_print
             at C:\projects\rust\src\libstd\sys_common\backtrace.rs:94
   1: std::panicking::default_hook::{{closure}}
             at C:\projects\rust\src\libstd\panicking.rs:354
   2: std::panicking::default_hook
             at C:\projects\rust\src\libstd\panicking.rs:371
   3: std::panicking::rust_panic_with_hook
             at C:\projects\rust\src\libstd\panicking.rs:549
   4: std::panicking::begin_panic<collections::string::String>
             at C:\projects\rust\src\libstd\panicking.rs:511
   5: std::panicking::begin_panic_fmt
             at C:\projects\rust\src\libstd\panicking.rs:495
   6: std::panicking::rust_begin_panic
             at C:\projects\rust\src\libstd\panicking.rs:471
   7: core::panicking::panic_fmt
             at C:\projects\rust\src\libcore\panicking.rs:69
   8: core::panicking::panic
             at C:\projects\rust\src\libcore\panicking.rs:49
   9: core::option::Option<&winit::platform::platform::events_loop::ThreadLocalData>::unwrap<&winit::platform::platform::events_loop::ThreadLocalData>
             at C:\projects\rust\src\libcore\macros.rs:21
  10: winit::platform::platform::events_loop::send_event::{{closure}}
             at E:\Rust\registry\src\github.com-1ecc6299db9ec823\winit-0.7.4\src\platform\windows\events_loop.rs:268
  11: std::thread::local::LocalKey<core::cell::RefCell<core::option::Option<winit::platform::platform::events_loop::ThreadLocalData>>>::with<core::cell::RefCell<core::option::Option<winit::platform::platform::events_loop::ThreadLocalData>>,closure,()>
             at C:\projects\rust\src\libstd\thread\local.rs:253
  12: winit::platform::platform::events_loop::send_event
             at E:\Rust\registry\src\github.com-1ecc6299db9ec823\winit-0.7.4\src\platform\windows\events_loop.rs:266
  13: winit::platform::platform::events_loop::callback
             at E:\Rust\registry\src\github.com-1ecc6299db9ec823\winit-0.7.4\src\platform\windows\events_loop.rs:305
  14: CallWindowProcW
  15: CallWindowProcW
  16: GetTopWindow
  17: KiUserCallbackDispatcher
  18: NtUserCreateWindowEx
  19: CreateWindowExW
  20: CreateWindowExW
  21: CreateWindowExW
  22: glutin::api::wgl::load_extra_functions
             at .\src\api\wgl\mod.rs:703
  23: glutin::api::wgl::Context::new
             at .\src\api\wgl\mod.rs:91
  24: glutin::platform::platform::context::Context::new
             at .\src\platform\windows\context.rs:71
  25: glutin::platform::platform::Context::new
             at .\src\platform\windows\mod.rs:69
  26: glutin::GlWindow::new
             at .\src\lib.rs:322
  27: window::main
             at .\examples\window.rs:11
  28: panic_unwind::__rust_maybe_catch_panic
             at C:\projects\rust\src\libpanic_unwind\lib.rs:98
  29: std::rt::lang_start
             at C:\projects\rust\src\libstd\rt.rs:51
  30: main
  31: __scrt_common_main_seh
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  32: BaseThreadInitThunk
```

**Comment by msiglreith** [comment]
After a bit of debugging the issue seems to be caused by the extra dummy window created for context creation:
* A new temporary window is created using the same callback function as the main window (https://github.com/tomaka/glutin/blob/master/src/api/wgl/mod.rs#L681-L711)
* The [callback function](https://github.com/tomaka/glutin/blob/master/src/api/wgl/mod.rs#L681-L711) recieves commands from both windows (the original and the dummy window), but only our original window has an associated event loop, which initialized the [thread-local data](https://github.com/tomaka/winit/blob/master/src/platform/windows/events_loop.rs#L258).
* [`send_event`](https://github.com/tomaka/winit/blob/master/src/platform/windows/events_loop.rs#L265-L270) and other [events](https://github.com/tomaka/winit/blob/master/src/platform/windows/events_loop.rs#L265-L270) get executed during the lifetime of the dummy window, trying to access the thread-local storage on the main thread, not the thread owned by the main event loop causing a panic.

What would be the best way to fix this? Just early-out on the mentioned places if there is no thread local data?

**Comment by tomaka** [comment]
Err thanks for the investigation. I really didn't think about that.
I think the proper fix would be to use a different window class, which is annoying.

**Comment by msiglreith** [comment]
Ok, thanks! I'll try to implement your solution as it sounds reasonable and better than the one I suggested.
